### ISSUE TITLE
Ubuntu v20: executables no longer work

### ISSUE THREAD

**Issue by franzlang** [ISISNeutronMuon/MDANSE#105]
Tried installing the latest commit from the `develop` branch inside a Singularity container using Ubuntu v20.04 and the GitHub actions artifact with the installation files (see here: https://github.com/ISISNeutronMuon/MDANSE/actions/runs/2476208199), but all the executables at `/usr/local/bin/` now give an error of the following form:
```
Singularity> mdanse_gui 
Traceback (most recent call last):
  File "/usr/local/bin/mdanse_gui", line 11, in <module>
    __import__('pkg_resources').run_script('MDANSE==1.5.0', 'mdanse_gui')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/mdanse_gui' not found in metadata at None
```
I can see the module installed via `python27 -m pip list` and import it via the python2 REPL. The commit used for the installation files published on the ISIS website (https://www.isis.stfc.ac.uk/Pages/MDANSEproject.aspx, commit [850b1313](https://github.com/ISISNeutronMuon/MDANSE/commit/850b1313)) works just fine.

**Comment by RastislavTuranyi** [comment]
Thanks for reporting this! I know what's going on and will fix it right away.
