### ISSUE TITLE
create basic tutorials from existing example scripts

### ISSUE THREAD

**Issue by franzlang** [ISISNeutronMuon/MDANSE#11]
use the existing example scripts/trajectories (e.g. https://mdanse.org/scripts/) and port them over to this Github project. create a basic set of tutorials/documentation about the scripts and their use-case/workflow. It may be useful to create Jupyter notebooks-style tutorials, particularly if the output can be meaningfully plotted.

**Comment by MBartkowiakSTFC** [comment]
We have a basic tutorial now, including scripts.
