### ISSUE TITLE
2D/3D Plotter cannot be opened from Plugins

### ISSUE THREAD

**Issue by RastislavTuranyi** [ISISNeutronMuon/MDANSE#113]
When an NetCDF data is loaded into MDANSE, the Plugins>Plotter>2D/3D Plotter cannot be opened and instead raises the following exception

```
C:\Program Files\MDANSE\lib\site-packages\mdanse-1.5.0-py2.7-win-amd64.egg\MDANSE\GUI\PluginsTreePanel.py -- 105 -- on_double_click -- self.TopLevelParent.panels["working"].active_page.currentWindow.drop(data)
C:\Program Files\MDANSE\lib\site-packages\mdanse-1.5.0-py2.7-win-amd64.egg\MDANSE\GUI\Plugins\IPlugin.py -- 169 -- drop -- plugin.plug()
C:\Program Files\MDANSE\lib\site-packages\mdanse-1.5.0-py2.7-win-amd64.egg\MDANSE\GUI\Plugins\PlotterPlugin.py -- 435 -- plug -- self._dataPanel.show_data()
C:\Program Files\MDANSE\lib\site-packages\mdanse-1.5.0-py2.7-win-amd64.egg\MDANSE\GUI\Plugins\PlotterPlugin.py -- 282 -- show_data -- self.datalist.SetStringItem(i, 4, self.dataproxy[var]['path'])
                                 
KeyError: 'path'
 
```

**Comment by RastislavTuranyi** [comment]
This is caused by `NetCDFInputData` not storing the paths while `NetCDFPlotterData` does store them. Therefore, there are two solutions that I can see:

1. Modify `DataPanel` in PlotterPlugin.py to only add the 'Path' column when the `PlotterPlugin.standalone == True`
2. Modify `NetCDFInputData` to use the same recursive variable-searching method as `NetCDFPlotterData` and store the paths along the way

@eurydice76, what do you think is the best course of action?

**Comment by eurydice76** [comment]
I think that we want this information to be also present in case of a plugin. So option 2 will be better. But take care to not duplicate code by externalizing the method that recursively search for NetCDF/HDF variables. I think that I already implemented it as a staticmethod so it should not be a big deal. A new module in Src/IO directorywould perfectly do the job.

**Comment by RastislavTuranyi** [comment]
When I do that, though, non-numeric variables are not loaded; is that desirable for the data loaded into MainFrame?

**Comment by eurydice76** [comment]
This was done on purpose as non numeric data are not taken in charge by the plotter so no need to display them.
