### ISSUE TITLE
Problem with the provided python interpreter in the windows installation

### ISSUE THREAD

**Issue by perenon** [ISISNeutronMuon/MDANSE#131]
After installation on Windows, the provided python interpreter appears to be flawed.

Indeed, if an user tries to load MDANSE within it (e.g. to launch a script), it will lead to the following error
```
C:\Program Files\MDANSE>.\python.exe -c "import MDANSE"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\MDANSE\lib\site-packages\mdanse-1.5.0-py2.7-win-amd64.egg\MDANSE\__init__.py", line 34, in <module>
    from MMTK import Database
  File "C:\Program Files\MDANSE\lib\site-packages\MMTK\__init__.py", line 39, in <module>
    from Scientific.Geometry import Vector
  File "C:\Program Files\MDANSE\lib\site-packages\Scientific\Geometry\__init__.py", line 26, in <module>
    isVector = Scientific._vector.isVector
AttributeError: 'module' object has no attribute 'isVector'

```

A quick test on the former ILL Windows installer shows that the problem might have been recently introduced
```
C:\Program Files\Institut Laue-Langevin\MDANSE>.\python.exe -c "import MDANSE"

```

**Comment by eurydice76** [comment]
Hi Rastislav, I assigned the issue to you as we have not the hand anymore on the build process at the ILL

**Comment by eurydice76** [comment]
We could solve partially the problem by setting manually the PATH as it is done in the MDANSE launcher bat file but this is just a quick fix. 

```
c:\Program Files\MDANSE>set dirname=%cd%
c:\Program Files\MDANSE>set PATH=%dirname%\Library;%dirname%\Library\bin;%dirname%\Library\include;%dirname%\Library\lib;%dirname%DLLs;%dirname%Include;%dirname%libs;%PATH%

```
We need a better solution as we should not expect the user to do this kind of thing. And moreover, as Remi mentionned, this used to work with the old installer.

**Comment by RastislavTuranyi** [comment]
I don't think there is a solution to this that does not involve manipulating paths. That said, the desired effect that MDANSE and all the other packages that come with it should be able to be imported from any shell can be achieved by editing the `site.py` file (corresponding to the [`site`](https://docs.python.org/2/library/site.html) builtin module) with the following lines:
```
mdanse_folder = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.environ['PATH'] = ';'.join([os.path.join(mdanse_folder, 'Library'), os.path.join(mdanse_folder, 'Library', 'bin'), os.path.join(mdanse_folder, 'Library', 'lib'), os.path.join(mdanse_folder, 'Library', 'include'), os.environ['PATH']])
```
This way, the PATH environmental variable is set to the desired value every time the python interpreter that comes with MDANSE is started, regardless of the shell used. Still, though, I'm not sure if altering a standard library module is a good idea; what do you think?

Also, by the way, if you have conda installed, you can activate the installed MDANSE as any other conda environment and everything will work:
```
(base) C:\Users\dni83241>conda activate "C:\Program Files\MDANSE"

(C:\Program Files\MDANSE) C:\Users\dni83241>python
Python 2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 17:26:54) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import MDANSE
>>> print MDANSE.__version__
1.5.0
>>>
```

**Comment by RastislavTuranyi** [comment]
Is doing this a good idea though?

**Comment by eurydice76** [comment]
For me it is OK.  I do not see any problem with this.

**Comment by RastislavTuranyi** [comment]
I have just found out that python statements can be used in .pth files, so I think a more friendly solution would be to, instead of  editing site.py, add mdanse.pth file to MDANSE\Lib\site-packages\ with the following content:
```
import os, sys; os.environ['PATH'] = os.path.join(sys.prefix, "Library", "bin") + os.pathsep + os.environ['PATH']
```

What do you think?

**Comment by eurydice76** [comment]
I do not  have much experience with pth files. If your solution works why not.

**Comment by eurydice76** [comment]
Take care it seems that pth files are used to alter sys.path not os.environ['PATH']. This are different things

**Comment by RastislavTuranyi** [comment]
That's not an issue since I the .pth file does not include a path but a python line that edits `os.environ['PATH']`, which is executed like a python script. 

Regardless of that though, it seems we are already using a custom site.py file in the CI/CD, so I'll just edit that.

**Comment by perenon** [comment]
Hi Rastislav,
Thank you for your prompt reply!

With Eric, we tested both your solutions this morning. We did not find any problem with the two versions.

After discussion, we think solution #2 you proposed appears to be the best since the alteration of the python package is minimal. The only reservation we have is the fact that .pth files are supposed to modify the sys.path (more or less the PYTHONPATH), not the system PATH. Nevertheless, we still consider this solution as the most elegant one.

Thanks once again.
Cheers,
Remi

**Comment by perenon** [comment]
One last thing before you merge, we are currently looking forward to find a solution for installing the pth during the `setup.py install` process instead of copying it afterward.

We come back to you soon.

**Comment by RastislavTuranyi** [comment]
I don't think that installing it during `setup.py install` is a good idea since the .pth file is only required in the specific case of the current Windows CI/CD. Other pipelines don't need it, and when MDANSE is built from source, it is not necessary either.

**Comment by eurydice76** [comment]
We were looking at creating a specific Windows case in the `setup.py` file but finally you right we should keep the current solution as it is the less invasive. So let's adopt the solution 2.

**Comment by perenon** [comment]
Last question (I hope :-)).

We already had 2 users (1 at ILL and 1 at FZJ) that came to us with this issue.
What is the best to finally give them a working version ?

Should we ask them to download 
- a version on the branch you created ?
- a version on the develop branch when the pull request will be merged ?
- an official release version (1.5.1 I guess) when it will be created ?

My personal preference goes to the second option since it is a good compromise between the quickness of the debugging and the fact to not spread any version to the users. But that is an open question !

Cheers,
Remi

**Comment by RastislavTuranyi** [comment]
I don't know, but I guess it depends on how urgently they need it? If it is required asap, in this case I think it should be ok to download from the PR since the changes were minor and they seem to be working. Otherwise, option 2 is fine if they can wait for a couple days, and if they can wait for a while, downloading a release is ideal.

**Comment by RastislavTuranyi** [comment]
That's a question for @sanghamitra-mukhopadhyay, and the short answer is that I don't know. There was originally no plan for 1.5.1 (I believe the plan was to go straight to 2.0.0 once work on protos is finished), but given that a couple issues have been found and solved, perhaps it would make sense (in my opinion) to do a quick minor release next week/the one after. That said, if Sanghamitra wants to first check a weird bug one person had in MDANSE school, that could take a while to contact them and fix it. Otherwise, there may also be other plans/considerations that I'm not aware of. Overall, the only thing I can say with certainty is that it's not going to be this week, since we have not discussed this.

**Comment by sanghamitra-mukhopadhyay** [comment]
Hi I am sorry for replying this late. I was ill so cannot see this. Yes, I support for a patch release as soon as possible. @RastislavTuranyi please update the Change.log and we can do the release in this week.
