### ISSUE TITLE
Add Delete option to File menu

### ISSUE THREAD

**Issue by RastislavTuranyi** [ISISNeutronMuon/MDANSE#141]
Currently, the only way to remove loaded trajectories from the main window of MDANSE is to use the 'delete' key on the keyboard. This method is very obscure, meaning that many users would not be aware of it, leaving them unable to remove trajectories. Therefore, a new button should be added to the the File menu that would provide another way to do this. This could, for example. open a window that would list all the loaded trajectories and a delete button that would remove the selected one.

**Comment by MBartkowiakSTFC** [comment]
In PR https://github.com/ISISNeutronMuon/MDANSE/pull/227 we added a drop-down menu that allows the user to delete a trajectory from the list of loaded trajectories. The menu is activated with the RMB.
