### ISSUE TITLE
MDANSE cannot be started on MacOS 12

### ISSUE THREAD

**Issue by RastislavTuranyi** [ISISNeutronMuon/MDANSE#147]
After installation, the MDANSE for MacOS cannot be started on MacOS 12. No error message is returned, but it appears to be caused by linking of the dylib libraries.

**Comment by sanghamitra-mukhopadhyay** [comment]
Okay, I see. I did not check on Mac 12.

**Comment by RastislavTuranyi** [comment]
Does everything work on the older version of Mac then?
