### ISSUE TITLE
Ubuntu 22 installer breaks certain system functionalities

### ISSUE THREAD

**Issue by ramic-k** [ISISNeutronMuon/MDANSE#151]
Hi Rastislav, 

as discussed here is the new issue. As described in https://github.com/ISISNeutronMuon/MDANSE/issues/135 once MDANSE is installed using installer provided there it breaks my bash (probably environment dependencies) and I do not have any more details than provided there. 

For example, after install I get the following issue when I open the terminal:
"**bash: /usr/local/lib/libtinfo.so.6: no version information available (required by bash)**"
and when I try to for example edit .bashrc with nano, which works fine prior to install, i get:
"**(base) ykr@W130289:/media/ykr/T7/working_folder$ nano ~/.bashrc 
nano: /usr/local/lib/libtinfo.so.6: no version information available (required by nano)
nano: /usr/local/lib/libtinfo.so.6: no version information available (required by nano)
nano: /usr/local/lib/libncursesw.so.6: no version information available (required by nano)
nano: /usr/local/lib/libncursesw.so.6: no version information available (required by nano)
Error opening terminal: xterm-256color.**"
Removing MDANSE fixes the above issues.

**Comment by ramic-k** [comment]
Which file did u end up removing? The one in conda/lib directory or?

**Comment by RastislavTuranyi** [comment]
On my VM, I just removed `/usr/local/lib/libtinfo.so.6` (there shouldn't be any `conda` directory installed by MDANSE). On our build servers, I have removed all libtinfo files that were in `$CONDA/envs/mdanse/lib` (which are the one that end up being moved to /usr/local/lib when you install MDANSE using the installer.

**Comment by ramic-k** [comment]
For some reason that didnt work for me. I guess i will re-install my Ubuntu and wait for the new CI/CD installer u create to try again.

**Comment by RastislavTuranyi** [comment]
Thank you, I can reproduce this so I'm having a look.

**Comment by RastislavTuranyi** [comment]
Ok, I think the [new build](https://github.com/ISISNeutronMuon/MDANSE/actions/runs/3009421555) should resolve this. Please let me know if any issues appear at any point, and thank you for your help.

**Comment by ramic-k** [comment]
Thank you for all your hardwork. Although nano does seem to open now, it still seems to print the same warning or whatever it is:

**(base) ykr@W132089:/media/ykr/T7/working_folder$ nano busy.bash 
nano: /usr/local/lib/libncursesw.so.6: no version information available (required by nano)
nano: /usr/local/lib/libncursesw.so.6: no version information available (required by nano)**

**Comment by ramic-k** [comment]
seems to be fine now! Thank you! I will update if I find anything off down the road!
