### ISSUE TITLE
Animation crashes on Windows 11

### ISSUE THREAD

**Issue by RastislavTuranyi** [ISISNeutronMuon/MDANSE#159]
When the Animation plugin is opened on Windows 11 obtained with the installer, the whole MDANSE freezes and then crashes without any error. Everything else works well enough, including the 3D plots and Density Superposition. There are no issues on Windows 10.

**Comment by ChiCheng45** [comment]
I've tested MDANSE on Windows 11 and the GUI loads up fine now.
