### ISSUE TITLE
Publish MDANSE documentation with Read the Docs

### ISSUE THREAD

**Issue by RastislavTuranyi** [ISISNeutronMuon/MDANSE#162]
Currently, the only place MDANSE documentation can be found is the docs bundled with MDANSE installers for the various platforms. Hosting this documentation with [Read the Docs](https://readthedocs.org/) (which is free) would make it more accessible and more visible, and it would also allow us to remove the documentation from the installers, making the MDANSE bundle smaller (the saving is not significant currently (just about 20 MB when unzipped), but it's something).

Furthermore, there continue to be issues with [mdanse.org](mdanse.org) (it is currently down) since it would cost money to host the website, and the upkeep of this custom website requires time investment and expertise. Placing the contents of mdanse.org into the Read the Docs website could allow us to easily maintain all the necessary information in one place, for free. Further, if the domain mdanse.org is desirable, it can be used to redirect to the Read the Docs website.

**Comment by MBartkowiakSTFC** [comment]
The MDANSE User Guide has been converted into a Read the Docs page:
https://mdanse.readthedocs.io/en/latest/
The API documentation is still included in the software itself.
