### ISSUE TITLE
Execution error on new MacBook Pro with M1 chip

### ISSUE THREAD

**Issue by sanghamitra-mukhopadhyay** [ISISNeutronMuon/MDANSE#17]
Compiled copy of MDANSE-1.5.0-beta-973a26f2-macOS-amd64 and MDANSE-1.5.0-beta-973a26f2-macOS-amd64.dmg don’t work on  MacBook Pro with M1 chip. It gives fatal error.

**Comment by gonzalezma** [comment]
@DBJochym proposed to try the following:
--------------------------------------------------------------------------------------------------------------------------------------------
 My understanding is that the M1 MacOS has a compatibility layer that attempts to take x86_64 binaries and translate them at run-time. This is not installed by default and "Rosetta 2" will need to be installed if not already. Normally, this is done on launch of the application as needed. There is a command line invocation that can be used if that doesn't happen automatically for some reason.

softwareupdate --install-rosetta

For the typical Mac user, this should be done on the "Terminal" app, followed by the "Enter" key.

If Rosetta doesn't do the trick, we would have to look at directing the user to compile the source and dependencies natively.
--------------------------------------------------------------------------------------------------------------------------------------------

However, the user reporting the issue (Michael Ohl from Juelich) tried this and did not work for him.
