### ISSUE TITLE
GUI for trajectory conversion crashes on MacOS 11 (x86 CPU)

### ISSUE THREAD

**Issue by MBartkowiakSTFC** [ISISNeutronMuon/MDANSE#172]
The problem has been described here:
https://github.com/ISISNeutronMuon/MDANSE/pull/164#issuecomment-1261308229

It seems that the wxPython libraries are trying to allocate excessive resources for no obvious reason. I originally thought that the issue may be related to the problem described here:
https://forum.kicad.info/t/kipython-scripting-console-greyed-out-extensions-not-working/36249/13

**Comment by MBartkowiakSTFC** [comment]
@sanghamitra-mukhopadhyay When you have the time, please check if this build works for you on your Mac. Several changes have been merged into this branch.
https://github.com/ISISNeutronMuon/MDANSE/suites/8667301331/artifacts/390236540

**Comment by eurydice76** [comment]
Hi @MBartkowiakSTF, do you have any news for this issue ?

**Comment by eurydice76** [comment]
Does the crash occur on a particular converter ? I can not reproduce it on my (ubuntu) machine so far.

**Comment by MBartkowiakSTFC** [comment]
I think that the crash occurs on dialog creation, before a converter is even started. If I understand it correctly, it happens for all of them.
I could not reproduce it either. On my Mac it works fine, and on my Ubuntu it is fine too.
A colleague from the Mantid team is testing it now on a Mac with an x86 CPU. We will see if he gets it to crash or not.

**Comment by MBartkowiakSTFC** [comment]
Martin checked the same build of MDANSE on a Mac with an x86 CPU, and he could not reproduce the problem either.

**Comment by sanghamitra-mukhopadhyay** [comment]
Unfortunately I am still facing the same problem to open the trajectory converter. My Mac is with 3.3 GHZ intel i7 processor.

**Comment by eurydice76** [comment]
Hi @sanghamitra-mukhopadhyay Can you give me the result of the command:

ls _crashing-directory_ | wc -l

where _crashing directory_ is the directory that is mentionned in the error message that you get.

**Comment by eurydice76** [comment]
Hi @MBartkowiakSTFC and @sanghamitra-mukhopadhyay, I just pushed on branch https://github.com/ISISNeutronMuon/MDANSE/tree/172_crashing_trajectory_converter_dialogs a putative fix for the crash that you experience on MacOS. The problem is with `os.listdir` function that can trigger some crashes for very populated directories. This is clearly a hack but I could not find better right now. @sanghamitra-mukhopadhyay could you please give a try with the newly built package for that branch ?

**Comment by eurydice76** [comment]
By the way, the build is crashing due to missing NetCDF.

**Comment by MBartkowiakSTFC** [comment]
Thanks for coming up with a correction to the code.
The NetCDF problem is new. Last time we built MDANSE, homebrew was still providing NetCDF 4.8.1, and in the failing build it is using 4.9.0. The new version _may have_ changed the location of the installed NetCDF in the filesystem, but I will have to check to know for sure.

**Comment by eurydice76** [comment]
Hi Maciej, I saw that the pipeline works again. Many thanks. However, as this workflow does not deploy. Would there be a way for you to deploy it so as Sanghamitra can check whether my implementation fixes the crash ?

**Comment by MBartkowiakSTFC** [comment]
Hi, I just merged the changes from my other branch, which were also needed to get MDANSE to build correctly on MacOS. There was a problem with modulegraph, needed by py2app. In any case, the current Action should build and deploy everything, so let's wait and see if there are no problems this time.

**Comment by MBartkowiakSTFC** [comment]
The last build seems to have worked fine:
https://github.com/ISISNeutronMuon/MDANSE/actions/runs/3249449621
I have just tried our the MacOS build on my computer. No problems so far.
@sanghamitra-mukhopadhyay please check if it works on your Mac.

**Comment by eurydice76** [comment]
Thanks Maciej, let's cross the fingers that my fix does the job ...

**Comment by sanghamitra-mukhopadhyay** [comment]
It is great @eurydice76 . This branch is working good on my Mac.  Thank you very much. :)
