### ISSUE TITLE
Last curve selected in 2D/3D Plotter remains in selected mode

### ISSUE THREAD

**Issue by gonzalezma** [ISISNeutronMuon/MDANSE#178]
When the Lines Settings option is used in the 2D/3D Plotter, the selected line changes to semi-transparent mode in the plot. This is expected and the semi-transparent curve changes correctly when another curve is selected. However, the last curve selected remains in that mode even after pressing the Apply button and closing the Lines Settings dialogue. As a consequence, the generated plot has always a curve plotted in semi-transparent mode whenever Lines Settings has been used. E.g.:
![image](https://user-images.githubusercontent.com/10974838/203325761-3f07bfc5-dbc9-4806-b1a1-9d0bd8032f05.png)

**Comment by eurydice76** [comment]
OK, I could find the bug. This is related to the fact that when closing the dialog the alpha value of the selected line is not set back to 1.0. I will fix it.

**Comment by MBartkowiakSTFC** [comment]
It works fine now, and does not block the interface either.
