### ISSUE TITLE
Set up Continuous integration and automatic testing using Github Actions

### ISSUE THREAD

**Issue by sanghamitra-mukhopadhyay** [ISISNeutronMuon/MDANSE#19]
The continuous integration has to be set up using Github action following the workflow given in gitlab-ci.yml . Automatic testing has to be included there as well.

**Comment by RastislavTuranyi** [comment]
Are we going to use a Github-hosted server, or are we going to host a server ourselves?

**Comment by RastislavTuranyi** [comment]
Do you want to translate gitlab-ci.yml into .yml that uses GitHub actions, or is it enough to use GitHub actions to wrap the already existing gitlab contibuous integration (using tools like described [here](https://github.com/marketplace/actions/mirror-to-gitlab-and-run-gitlab-ci) or [here](https://www.youtube.com/watch?v=qgl3F2j-1cI&t=140s))?

**Comment by sanghamitra-mukhopadhyay** [comment]
Translating the gitlab-ci.yml  to git hub is required for future upgrade. A mirroring can be a starting point.

**Comment by sanghamitra-mukhopadhyay** [comment]
Yes, we will use github hosted server, not our own.

**Comment by RastislavTuranyi** [comment]
In that case, should I create new dockerfiles for Ubuntu 20.04, or are we going to only test on ubuntu 18.04?
