### ISSUE TITLE
Improve the ASCII output of MDANSE analysis

### ISSUE THREAD

**Issue by eurydice76** [ISISNeutronMuon/MDANSE#191]
When the output format selected for the is "ASCII", the corresponding ASCII files could be improved. Indeed, so far, they just contain the output variable but not the the one they are depending on. Doing this would make those files auto-sufficient.

**Comment by MBartkowiakSTFC** [comment]
Closed by the PR:
https://github.com/ISISNeutronMuon/MDANSE/pull/192
