### ISSUE TITLE
investigation: dependencies and requirements

### ISSUE THREAD

**Issue by franzlang** [ISISNeutronMuon/MDANSE#2]
investigate and understand what python packages/modules the current MDANSE code depends on. this includes:

- python version required
- custom ILL scipy module required: https://code.ill.fr/scientific-software/scientific-python
- custom ILL mmtk module required: https://code.ill.fr/scientific-software/mmtk
- any other python modules required to compile/run the code and any existing tests
- any non-python dependencies required to compile/run the code

From this create:
- documentation about any non-standard/custom dependencies, e.g. how MDANSE depends on the custom scipy and mmtk module. 
- separate issues if we need to fork/clone the scipy/mmtk modules from the ILL gitlab pages
- a `requirements.txt` file capturing the required "standard" python modules

**Comment by sanghamitra-mukhopadhyay** [comment]
Pyro is used for parallel execution of the code using the concept of master slave based parallel processing.  Pyro can be installed from here: https://pyro4.readthedocs.io/en/stable/install.html. MDANSE is using older version of Pyro, Pyro4 or less, which are now obsolete.

**Comment by MBartkowiakSTFC** [comment]
The investigation was completed and subsequently used for planning the move to Python 3.
