### ISSUE TITLE
AtomsListConfigurator gets wrong values from UserDefinition

### ISSUE THREAD

**Issue by MBartkowiakSTFC** [ISISNeutronMuon/MDANSE#205]
In MDANSE 1.5.2, and presumably the older versions as well, AtomsListConfigurator makes OrderParameter, AngularCorrelation and SpatialDensity fail at runtime.

At least two problems exist at the moment:
1. AtomsListConfigurator tries to find the requested "atom list" (which is really a dictionary) in
`UD_STORE.get_definition(trajConfig["basename"],"%d_atoms_list" % self._nAtoms,value)`
which would mean that `'2_atoms_list'` should be the key. However, the definitions are really stored under `'atoms_list'` without the preceding number.
2. The dictionary retrieved above is assigned to the `molecule, atoms` tuple. This assigns the *keys* of the dictionary to the variables, giving us
`molecule = 'natoms'`
`atoms = 'indexes'`
which makes the subsequent call to `find_atoms_in_molecule(trajConfig['instance'].universe,molecule, atoms, True)` return an empty list every time.

It is necessary to correct AtomsListConfigurator.py, lines 65-71, in order to make AngularCorrelation and OrderParameter run. I am still not sure at this stage what additional changes are needed to make SpatialDensity work as well.

**Comment by MBartkowiakSTFC** [comment]
Branch
https://github.com/ISISNeutronMuon/MDANSE/tree/205-fix-AtomsListConfigurator
has been created to fix the problem.

**Comment by gonzalezma** [comment]
Question (we can discuss this on next call): Should we really fix this issue (as well as any pending issues)? I thought we had agreed that 1.5.2 would be the last "python 2" release. Then the priority would be to have a working version of "python 3" mdanse and start solving the pending issues directly in that version.

**Comment by MBartkowiakSTFC** [comment]
Yes, this is an excellent question, and I did have a discussion about it today. The main reason why I proposed to fix some of it is because it took hardly any time. Also, apparently there is a user who wanted it fixed.

I agree that we should talk about it during our next call.
