### ISSUE TITLE
Black as automatic code formatter

### ISSUE THREAD

**Issue by MBartkowiakSTFC** [ISISNeutronMuon/MDANSE#217]
Since it would be good to have some reproducible standard for code formatting, I would suggest that we start using Black as a code formatting tool:
https://black.readthedocs.io/en/stable/
It seems to be quite good at making the code follow the standards, and it does not break anything.

**Comment by MBartkowiakSTFC** [comment]
Implemented in this PR:
https://github.com/ISISNeutronMuon/MDANSE/pull/223

**Comment by eurydice76** [comment]
I am a bit reluctant to use this kind of tools which suggest me how I should program in term of line length, size of functions and bullshits like this. They introduced this in Mantid and when you see how the soft looks like in term of functionnality, ergonomy and bugs I just smile strong and loud.

**Comment by MBartkowiakSTFC** [comment]
From another perspective, this solution requires only minimum effort from everyone involved. The procedure is:
1. Write the code any way you like,
2. Run `black Src/`,
3. Commit the changes.

We have had this issue on our list for over a year:
https://github.com/ISISNeutronMuon/MDANSE/issues/52
and now it is fixed. So, I will continue using the automatic formatter, mainly because this way I don't have to remember when to use`'` and when `"`, as it will all be replaced consistently in the end.
