### ISSUE TITLE
MoleculeFinder vs. com_trajectory.pyx

### ISSUE THREAD

**Issue by MBartkowiakSTFC** [ISISNeutronMuon/MDANSE#239]
Elastic Incoherent Scattering Factor and Gaussian Dynamic Incoherent Scattering Factor both fail when run on a trajectory created with MoleculeFinder.

Currently, MoleculeFinder has two functions:
1. Finds atoms connected with covalent bonds, by comparing interatomic distances to the covalent radii.
2. Translates atoms by unit cell vectors to place atoms belonging to the same molecule next to each other.

The resulting trajectory works well for most analysis types, but fails when the Cython function `MDANSE.Extensions.com_trajectory._recursive_contiguity` is called.

```
               com_traj = com_trajectory.com_trajectory(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             File "Extensions/com_trajectory.pyx", line 133, in MDANSE.Extensions.com_trajectory.com_trajectory
             File "Extensions/com_trajectory.pyx", line 49, in MDANSE.Extensions.com_trajectory._recursive_contiguity
           TypeError: an integer is required
```

It is possible that the way the bond information is stored has changed, and is not compatible with `com_trajectory`.

**Comment by ChiCheng45** [comment]
fixed by #277
