### ISSUE TITLE
Logo Redesign, Colour Scheme Changes, and Improve the Read the Docs look 

### ISSUE THREAD

**Issue by ashmeigh** [ISISNeutronMuon/MDANSE#257]
Propose a redesign of the project's logo and updates to the colour scheme to give our project a fresh and modern look. Additionally, we aim to integrate the ISIS logo into our Read the Docs documentation for consistency and branding.

**Comment by MBartkowiakSTFC** [comment]
The new colour scheme is being used now, the new logo is part of the documentation, and the UKRI/STFC logo is in our splash screen. I think that this is close enough to the goals set in this issue for it to be closed now.
