### ISSUE TITLE
Develop Ongoing GUI Tutorials

### ISSUE THREAD

**Issue by ashmeigh** [ISISNeutronMuon/MDANSE#258]
Building upon the creation of a series of comprehensive GUI tutorials for the users with the knowledge and skills needed to effectively navigate and utilize the graphical user interface (GUI). The plan is to continue developing and expanding the GUI tutorials. These tutorials will provide step-by-step guidance, practical examples, and real-world use cases, catering to users of all experience levels. The goal is to create an ever-evolving library of tutorials that cater to various aspects of GUI usage, addressing specific tasks, workflows, and advanced functionalities.

By documenting essential GUI workflows, this ensures that the necessary content is readily available for video creation when the time comes. This will allow us to create tutorial videos separately in the future, enhancing user onboarding and providing additional resources for our users.

**Comment by MBartkowiakSTFC** [comment]
Initial tutorial has been implemented. The issue can be closed since it is very general.
