### ISSUE TITLE
ENHANCEMENT: Improve 'simple help' readability

### ISSUE THREAD

**Issue by RastislavTuranyi** [ISISNeutronMuon/MDANSE#28]
Firstly, when simple help is opened from the help menu, the window that opens is very small. Secondly, the opened text is all plain, which makes it difficult to read it as well as to quickly find relevant information. Fixing this should improve the user experience but shouldn't take much effort.

**Comment by RastislavTuranyi** [comment]
I have pushed a commit that added the superscripts.

**Comment by eurydice76** [comment]
Perfact. Thanks Rastislav for the improvement. I guess we can merge.

**Comment by RastislavTuranyi** [comment]
Yes, I would say so, but for consistency, it would probably be best to do that via a PR. Do you want to open a PR for this work, or would you like me to do it instead?
