### ISSUE TITLE
[BUG] MDANSE_GUI fails to start with PyQt5 backend

### ISSUE THREAD

**Issue by MBartkowiakSTFC** [ISISNeutronMuon/MDANSE#295]
**Description of the error**
MDANSE_GUI uses qtpy, and should work with PyQt5, PyQt6, PySide2 and PySide6. However, on platforms where PyQt6 is not available and PyQt5 has to be used instead, the MolecularViewer module does not initialise correctly.

**Describe the expected result**
The GUI should start and work the same when PyQt6 is replaced by PyQt5.

**Describe the actual result**
in MolecularViewer.py, line 84:
`self._iren = QVTKRenderWindowInteractor(self)`
`argument 1 has unexpected type 'MolecularViewer'`

**Suggested fix**
If there is a way to import QVTKRenderWindowInteractor through qtpy, we should use it. Otherwise we need to check how VTK chooses which version of QVTKRenderWindowInteractor it provides.

**Additional details**
N/A

**Comment by ChiCheng45** [comment]
@MBartkowiakSTFC I've tested this on Windows and Ubuntu with pyqt5 and mdanse loads up fine. Can you test on Mac? I think this can be closed now.

**Comment by MBartkowiakSTFC** [comment]
I checked it, and it worked for me too.
