### ISSUE TITLE
MDANSE crashes during trajectory conversion of Gromacs files

### ISSUE THREAD

**Issue by sanghamitra-mukhopadhyay** [ISISNeutronMuon/MDANSE#31]
MDANSE crashes during trajectory conversion of Gromacs files. This particular file is of about 20000 atoms and the trajectory file is about 3GB.

**Comment by RastislavTuranyi** [comment]
The error causing the crash is as follows:
```
c:\users\dni83241\appdata\local\temp\MDANSE_dni8_26884_88nk1v.pyht9nwv -- 24 -- <module> -- gromacs.run(parameters,status=True)
C:\Program Files\MDANSE\lib\site-packages\mdanse-1.5.0-py2.7-win-amd64.egg\MDANSE\Framework\Jobs\IJob.py -- 325 -- run -- raise JobError(self,tb)
C:\Program Files\MDANSE\lib\site-packages\mdanse-1.5.0-py2.7-win-amd64.egg\MDANSE\Framework\Jobs\IJob.py -- 46 -- __init__ -- tback = traceback.extract_stack()

Traceback (most recent call last):
  File "C:\Program Files\MDANSE\lib\site-packages\mdanse-1.5.0-py2.7-win-amd64.egg\MDANSE\Framework\Jobs\IJob.py", line 303, in run
    self.initialize()
  File "C:\Program Files\MDANSE\lib\site-packages\mdanse-1.5.0-py2.7-win-amd64.egg\MDANSE\Framework\Jobs\Gromacs.py", line 52, in initialize
    self.numberOfSteps = len(self._xtcFile)
  File "Extensions\xtc\xtc.pyx", line 589, in MDANSE.Extensions.xtc.XTCTrajectoryFile.__len__
  File "Extensions\xtc\xtc.pyx", line 566, in MDANSE.Extensions.xtc.XTCTrajectoryFile.offsets.__get__
  File "Extensions\xtc\xtc.pyx", line 528, in MDANSE.Extensions.xtc.XTCTrajectoryFile._calc_len_and_offsets
RuntimeError: error during seek: status code fseek=13; offset=35404, last_pos=2147462660
```

The issue is that the function `xdr_seek` returns a value different from 0. This function is referenced in multiple files, but I believe that it is ultimately defined in [xdr_seek.c](https://github.com/ISISNeutronMuon/MDANSE/blob/develop/Extensions/xtc/src/xdr_seek.c) file.

**Comment by RastislavTuranyi** [comment]
Interestingly, performing the operation, ie. constructing an instance of the `XTCTrajectoryFile` class, on the command line takes place without issues:
![image](https://user-images.githubusercontent.com/78977041/155103992-04760714-dd06-400e-83c3-91bbedbb6949.png)

This seems like a temporary solution for the user.

**Comment by RastislavTuranyi** [comment]
The issue indeed lies somewhere in the C and Cython files, but it is difficult to pinpoint where. The low-level function that is being called through the `xdr_seek` wrapper is `fseek`, at least for the cases where the error ocurrs, and it returns a value of `-1.` The C errorno is 22, referring to [an invalid argument for a function](https://docs.microsoft.com/en-us/cpp/c-runtime-library/errno-constants?view=msvc-140), but that said, the only value that changes inside the while loop where this function is called is the `byte_offset` variable (file is the same and origin is always `SEEK_CUR`).

Interestingly, this failing operation, ie. evaluating the length of the trajectory, also fails in MDTraj 1.9.3 with python 2.7 (MDTraj is a package from where this XTC reader has been copied), but it works without issues with MDTraj 1.9.7 with python 3.10. I have tried copying files from the latest version of MDTraj to replace current reader, but the error is the same.

**Comment by RastislavTuranyi** [comment]
The reason why the conversion keeps failing is indeed the `fseek` function (probably because it is not equipped to deal with the data in the file), but rather than its presence, the issue is that it gets called at all. What should happen on Windows, like in the `xdrstdio_setpos` function, is that the `_fseeki64` function should be called, but because `_MSVC_VER ` is not defined, it gets skipped over.
