### ISSUE TITLE
[BUG] DL POLY atom label parsing issue

### ISSUE THREAD

**Issue by ChiCheng45** [ISISNeutronMuon/MDANSE#335]
**Description of the error**
Converting certain dlpoly files leads to a MDANSE trajectory file incorrect atoms. Converting the water with velocities from MDANSE-Examples can lead to a trajectory with waters that have two oxygens. For this case the issue occurs because it incorrectly assigns the point charge on tip4p to a oxygen atom.

**Describe the expected result**
A trajectory of waters with the correct number of atoms.

**Additional details**
This occurs in both the old and new versions of MDANSE.

![image](https://github.com/ISISNeutronMuon/MDANSE/assets/14276033/bfab1a27-772d-41fc-bb9a-b3d0dc7323fa)

**Comment by gonzalezma** [comment]
I would say this is the correct TIP4P geometry. The important point is that the 4th position is assigned to a dummy or special atom, and not to an oxygen atom. But it should be retained as it could be needed to e.g. compute the molecular dipole moment.
