### ISSUE TITLE
[ENHANCEMENT] [BUG] What should be done with mass information from MD outputs?

### ISSUE THREAD

**Issue by ChiCheng45** [ISISNeutronMuon/MDANSE#336]
**Is your feature request related to a problem? Please describe.**
In DL POLY atomic masses are specified in the field file. As far as I can tell MDANSE ignores this and uses the masses it has stored internally in the atoms database. I'd imagine something similar occurring in a lot of other convertors as well. This seems like an issue since for example I may run a MD simulation with heavier isotopes by changing its mass, MDANSE could then pick the wrong isotope if it reads the output data from the atomic symbol used. 

**Describe the solution you'd like**
Perhaps the atom mapping as suggested in #334 should be done for all convertors to ensure no assumption are made. This also has the benefit that the atom_transmutation could be removed since this could be done using the mapping.

**Comment by gonzalezma** [comment]
Nothing against, but just two comments:
1. Using the masses to identify the elements/isotopes is not always unambiguous, as the known problems with the Lammps converter show. It would be good to have a list of the different isotopes that have the same mass (within the typical tolerance that a user could use in the input file, I would say 0.001 or even 0.01 amu) and some way of  discriminating between them when the mass alone cannot be used to choose the right element.
2. I would not remove the atom transmutation. I think you can still have a single simulation and want to calculate the expected output for two different isotopes without needing to redo the simulation or change manually the input files to modify some masses.
