### ISSUE TITLE
[BUG] Some 2d plot previews are not oriented correctly

### ISSUE THREAD

**Issue by ChiCheng45** [ISISNeutronMuon/MDANSE#376]
**Description of the error**
After running the neutron dynamic total structure factor and loading up the MDA file into the plot window the preview is rotated by 90 degrees compared to the full figure.

This seems to only affect a few results.

**Additional details**
f(q,t)_coh_weighted_OO - preview rotated
![image](https://github.com/ISISNeutronMuon/MDANSE/assets/14276033/3062aabf-3b89-4303-b714-128e8f64cffb)

f(q,t)_inc_total - preview the same
![image](https://github.com/ISISNeutronMuon/MDANSE/assets/14276033/3fc1c961-8b91-413e-9276-4403eeee84a5)

**Comment by MBartkowiakSTFC** [comment]
We don't have previews in the new plotting interface.
