### ISSUE TITLE
[BUG] Frames widget does not detect the trajectory length correctly

### ISSUE THREAD

**Issue by MBartkowiakSTFC** [ISISNeutronMuon/MDANSE#383]
**Description of the error**
Frames widget automatically sets the inputs to 0, 100, 1 for trajectories with more than 100 steps.

**Describe the expected result**
The Frames widget should set the limits on each of the three fields to (0, len(trajectory)), and set the values of the three fields to 0, len(trajectory), 1.

**Describe the actual result**
For short trajectories everything works as expected. If a trajectory ends on frame 5, the Frames widget will show 0, 5, 1.
For longer trajectories (e.g. 1800 frames) the Frames widget shows 0, 100, 1.

**Suggested fix**
Since the mechanism of filling in the fields works in some cases, it probably just needs to be adjusted.

**Additional details**
N/A

**Comment by ChiCheng45** [comment]
I've done some testing and I did find that if you had different trajectory with the same name then the actions wouldn't update which might have caused the issue that you've seen. In all other cases it seems to work fine. Let's close this with the fix in #410.

![Animation14](https://github.com/ISISNeutronMuon/MDANSE/assets/14276033/30dda7a1-a229-4e57-a81e-4ae3ef7aef0b)
