### ISSUE TITLE
[BUG] Trajectory editor jobs and atom selection

### ISSUE THREAD

**Issue by ChiCheng45** [ISISNeutronMuon/MDANSE#384]
**Description of the error**
If you run the cropped trajectory job with atom selection the MDT file is not filled in an expected manner. For example when I run crop trajectory with all atoms selected except for water molecule atoms all atoms are retained in the MDT file. The only differences is the coordinates of the atoms which are not selected are not stored and have nan values for their coordinates. 

The nan values lead to a crash when you run the bonding in the 3D view. Jobs appear to be able to be completed but this can cause nan values to occur in the MDA results file which mean that the plot window is unable to plot the results correctly.

**Describe the expected result**
It should've returned a MDT file with a chemical system and configuration of only the selected atoms.

**Additional details**
Before cropping
![image](https://github.com/ISISNeutronMuon/MDANSE/assets/14276033/bd045f14-5cd5-4ce6-9ad3-ca74484eb990)

After cropping - note that the water molecules are not drawn because their coordinates are nan
![image](https://github.com/ISISNeutronMuon/MDANSE/assets/14276033/de232063-0bec-44fd-b981-3389522d4248)

Plotting the VACF of the DFTB H2O trajectory with one oxygen removed
![image](https://github.com/ISISNeutronMuon/MDANSE/assets/14276033/5178e6e0-a7a8-4677-b812-010363acaa06)

**Comment by MBartkowiakSTFC** [comment]
CroppedTrajectory has been replaced by TrajectoryEditor which does not create this problem.
