### ISSUE TITLE
[BUG] Update the information panel data in the actions tab

### ISSUE THREAD

**Issue by ChiCheng45** [ISISNeutronMuon/MDANSE#407]
**Description of the error**
Update the information panel data in the actions tab so that it is more readable. 

**Suggested fix**
Perhaps it should be changed so that panel is some sort of file viewer, perhaps it should be a preview of some parts of the documentation instead.

**Additional details**
Some parts that need to be improved.

![image](https://github.com/ISISNeutronMuon/MDANSE/assets/14276033/27e41096-692f-4b9d-9bba-6c95eba20413)

**Comment by MBartkowiakSTFC** [comment]
This has been modified so that the information is output as an HTML table.
