### ISSUE TITLE
ENHANCEMENT: Increase the default size of the variable box in 2D/3D Plotter

### ISSUE THREAD

**Issue by RastislavTuranyi** [ISISNeutronMuon/MDANSE#42]
At the moment, the variable box in 2D/3D Plotter is only large enough to fit one row by default, which makes selecting a variable tedious, especially in analyses with lots of variables like PDF. Therefore, the default size should be increased at the file box's expense.

Furthermore, the only way to change the size of the variable box is to resize the whole Plotter window. Manual resizing of these boxes should be implemented. This would work similarly to how the various panels in the main window can be resized.

**Comment by eurydice76** [comment]
I have not practised `wxPython` for years but I will give a try because I experienced the described behavior and it is very annoying.

**Comment by eurydice76** [comment]
I added a splitter window between the dataset and the data lists and also increased a bit the minimal size of the mainn frame. What do you think ?

**Comment by RastislavTuranyi** [comment]
Looking at the GUI, the initial size is increase is great, and the ability to resize is also useful. However, do you think it would be possible to limit the ability to resize to prevent the two parts of the Data panel from overlapping? Currently, it is possible to essentially delete the 'variables' part of the Data panel, like so:
![image](https://user-images.githubusercontent.com/78977041/162001210-31215791-31d9-4cb2-9ab2-fc9da006c550.png)
To reproduce, just resize all the way down, and then maximize the plotter window. This completely hides the 'variables' part and also hides the ability to resize.

Similar effect can be achieved by resizing the 'variables' part all the way up, which hides the 'filename', though this time the ability to resize remains intact. Still, I think this could cause confusion.
![image](https://user-images.githubusercontent.com/78977041/162002197-b444f510-66dc-4285-851b-176627b994a9.png)

**Comment by eurydice76** [comment]
ok, I will try to solve this

**Comment by eurydice76** [comment]
I could resolve the bottom to up problem, but the problem still exists for the top to bottom direction. I suspect a bug on wxPython or at least something I misunderstand from their API.

**Comment by eurydice76** [comment]
I think it is OK now. The dataset and data panels now have a minimal size. Does it fulfill your expectations ?

**Comment by RastislavTuranyi** [comment]
I have some comments that I would like to discuss, but I think it would be easier do it using the functionalities that a PR provides. Can you please open one? Thanks!

**Comment by eurydice76** [comment]
I just created the PR
