### ISSUE TITLE
[BUG] On Mac `File -> Open` in top-bar, not GUI bar

### ISSUE THREAD

**Issue by oerc0122** [ISISNeutronMuon/MDANSE#424]
**Description of the error**
On a mac, it seems that the open dialogue for the plotting interface is in the top-bar not the main bar. This is probably due to how macs interface with QT sub-windows. 

**Suggested fix**
Eventually plan is apparently to move the plot sub-window to a tab which will hopefully solve this issue, however, it is worth noting here to ensure this is checked.

**Comment by MBartkowiakSTFC** [comment]
The plotting dialog has been replaced with plotting tabs, and the menu is not an issue in the current version.
