### ISSUE TITLE
ENHANCEMENT: Implement TRR reading into Gromacs converter

### ISSUE THREAD

**Issue by RastislavTuranyi** [ISISNeutronMuon/MDANSE#43]
Specific implementation of #27 for Gromacs converter.

Currently, MDANSE is able to convert only XTC files from Gromacs simulations. However, these files do not contain velocity data since they are highly compressed. A Gromacs file format which does contain this and other information is TRR, but it is not currently implemented in MDANSE. Given that multiple analyses require velocity data, it would be useful to remedy this. The C and cython files for TRR parsing already do exist within MDANSE, since they were taken from MDTraj code along with those for XTC parsing, so all that is required is to write code in python within the main codebase to wrap and utilise these classes as well as create a complimentary GUI.

**Comment by eurydice76** [comment]
I can give a try but I have no TRR trajectory at hand. Could you send me a small one if you have any ?

**Comment by RastislavTuranyi** [comment]
@eurydice76, if you pull the branch from #44, there are 2 new TRR trajectories included in the Data/Trajectories/Gromacs. There are also corresponding XTC trajectories which can be used for comparison. In fact, I have written a new test as well that uses these trajectories, so you can just use that to test the PR.

**Comment by eurydice76** [comment]
By the way, are you sure that TRR file actually stores the velocities and the forces ? From the mdtraj documentation:"The .trr format is a cross-platform compressed binary trajectory format produced by the gromacs software that stores atomic coordinates, boxvectors, and time information".

**Comment by RastislavTuranyi** [comment]
It can, but it does not have to. For example, one of the included trajectories, adk_oplsaa.trr, contains only velocities, but the other one, corbotoxin.trr, contains both velocities and forces.
