### ISSUE TITLE
[BUG] Change default r and q values for the static structure factor

### ISSUE THREAD

**Issue by ChiCheng45** [ISISNeutronMuon/MDANSE#473]
**Description of the error**
As done for the PDF job (#470) the static structure factor default r and q values need to be updated so the results are meaningful.

Here is the static structure factor with the current default values (0 to 10 step 1 for both r and q).
 
![image](https://github.com/ISISNeutronMuon/MDANSE/assets/14276033/0d117fb9-cea3-4d85-a0db-1ee622430cbf)

Here is what I get when I change the step size for both q and r to 0.01 for example.
![image](https://github.com/ISISNeutronMuon/MDANSE/assets/14276033/2990afb7-58ea-4958-aaa3-6ae1032db626)

**Comment by gonzalezma** [comment]
The value at Q=0 is also not meaningful. If you want/can do a further modification, it would be useful to set by default Qmin = (2*pi)/Lmax, where Lmax would be the largest dimension of the simulation box.
