### ISSUE TITLE
[BUG] Why are there large negative values of the static structure factor as q->0

### ISSUE THREAD

**Issue by ChiCheng45** [ISISNeutronMuon/MDANSE#474]
**Description of the error**
Why does the static structure factor have a large negative value for q->0. Here is one I generated using a cp2k water trajectory. I'd imagine there are numerical issues as q=0 but the drop to a large negative value begins before it gets close to 0.

![image](https://github.com/ISISNeutronMuon/MDANSE/assets/14276033/cd37a29a-7d42-4fcb-9460-5e7db1fd817d)

Here is an experimental static structure factor of liquid Ar (https://journals.aps.org/pra/abstract/10.1103/PhysRevA.7.2130).

![image](https://github.com/ISISNeutronMuon/MDANSE/assets/14276033/9ddebba8-8f55-4973-8701-5db30b6f4b01)

it goes to zero as q->0.

**Comment by gonzalezma** [comment]
I just answered in the other issue. From a physical point of view, the minimum Q that makes sense in the simulation is the (1,0,0) vector. Here we calculate S(Q) as the FT of the g(r), so the Q-range chosen is arbitrary, but any Q value below that Qmin is not meaningful. In particular, for Q=0 the exp term is 1 and you will get a number that is proportional to the sum of all the scattering lengths of the atoms in your system.
