### ISSUE TITLE
BUG: Toggle Toolbar button hides panel headers instead of toolbar

### ISSUE THREAD

**Issue by RastislavTuranyi** [ISISNeutronMuon/MDANSE#48]
In GUI, the Toggle toolbar option in the View menu hides the headers of the Data panel and the Working panel instead of the toolbar.
![image](https://user-images.githubusercontent.com/78977041/159685765-74c6e8ea-e52a-48bc-88fd-9bd9c555e4fd.png)
![image](https://user-images.githubusercontent.com/78977041/159685782-fe88166b-8699-408e-bbc0-50cb6a33ca0d.png)

**Comment by eurydice76** [comment]
I could not reproduce this on a conda installed version of MDANSE (wxPython version 3.0.2)

**Comment by RastislavTuranyi** [comment]
Indeed, I have tested with the CI/CD installer on Ubuntu 20.04, and I have not observed this bug. However, whether I got wxPython and VTK from wheels or from Conda, the bug persists. @sanghamitra-mukhopadhyay, can you please use a CI/CD installer to check if this bug occurs on MacOS? If not, this is purely a windows issue and probably related in some way to #30.
