### ISSUE TITLE
investigation: dependency on ILL scipy module

### ISSUE THREAD

**Issue by franzlang** [ISISNeutronMuon/MDANSE#5]
investigate what parts of the code depend on the custom `scipy` module released by the ILL (https://code.ill.fr/scientific-software/scientific-python) that the MDANSE code currently requires. also gain an understanding of and document why we could or could not use the "standard" `mmtk` module from [pypi.org](https://pypi.org/). if required: create issues for the different parts of the code that need to be updated so that we can use the standard `scipy` module.

**Comment by sanghamitra-mukhopadhyay** [comment]
ILL Scipy is only used in calculations of "rigid atoms". This necessity can be avoided by redesigning the "rigid atom" calculations.

**Comment by MBartkowiakSTFC** [comment]
This work is already completed. Python 3 version does not depend on ScientificPython.
