### ISSUE TITLE
STYLING: inconsistent use of single or double quotes for strings throughout all the code

### ISSUE THREAD

**Issue by eurydice76** [ISISNeutronMuon/MDANSE#52]
The strings throughout the code sometimes use single quote, sometimes use double quotes. This is of course just styling, but we should decide which format to use once for all and stick on it from now. I have not any strong opinion on which format to use between single and double quotes. Perhaps we should have a look at the one that is the more used in the code and select this as the reference.

**Comment by MBartkowiakSTFC** [comment]
Now that we use black for code formatting, the quotes will follow the same formatting standard throughout the code.
