### ISSUE TITLE
BUG: PDF total are calculated incorrectly

### ISSUE THREAD

**Issue by RastislavTuranyi** [ISISNeutronMuon/MDANSE#56]
When one of the PDF functions evaluates to 0 at all r-values (e.g. intramolecular PDF for water oxygens), the total PDFs calculated from these constituents also evaluate to 0 at all r-values:
![image](https://user-images.githubusercontent.com/78977041/162452939-ba0e32fb-dc66-4a15-9ade-bdcac9909da6.png)
![image](https://user-images.githubusercontent.com/78977041/162453116-5af35b11-1981-4e95-9ffc-23946f28ccf8.png)
![image](https://user-images.githubusercontent.com/78977041/162453177-0ac84a3c-b9e7-4d60-a7bd-b7edabace207.png)

This is incorrect and very unhelpful. Instead, the totals should evaluate to a non-zero value, like they do in nMOLDYN:
![image](https://user-images.githubusercontent.com/78977041/162453620-63a32885-c958-4852-b060-8032610b7b7d.png)
![image](https://user-images.githubusercontent.com/78977041/162453711-235c4aa9-705e-4b15-9729-622abc80b9b3.png)
![image](https://user-images.githubusercontent.com/78977041/162453820-c59e1c72-558d-454f-9989-3986dedc0e1e.png)

**Comment by eurydice76** [comment]
@gonzalezma could you please have a look on this ?

**Comment by gonzalezma** [comment]
Yes, I will look to this. It's quite strange and I'm pretty sure that it was not the case before. But let me check ...

**Comment by gonzalezma** [comment]
@RastislavTuranyi How did you get your result? I get the expected pdf (with total_OO = inter_OO and intra_OO = 0):
![water_pdf](https://user-images.githubusercontent.com/10974838/162475413-1208e15b-2d6f-4f27-97c6-43b49665ea2d.png)

**Comment by gonzalezma** [comment]
Has the pdf analysis been modified recently?

**Comment by RastislavTuranyi** [comment]
You are right! I checked with an older build, and I am also getting correct results. Yes, we have modified the PDF analysis to calculate RDF and TCF like it does in nMOLDYN, but I did not change the PDF calculation. Let me go and check this.
