### ISSUE TITLE
investigation: dependency on ILL mmtk module

### ISSUE THREAD

**Issue by franzlang** [ISISNeutronMuon/MDANSE#6]
investigate what parts of the code depend on the custom `mmtk` module released by the ILL (https://code.ill.fr/scientific-software/mmtk) that the MDANSE code currently requires. also gain an understanding of and document why we could or could not use the "standard" `mmtk` module (https://github.com/khinsen/mmtk). if required: create issues for the different parts of the code that need to be updated so that we can use the standard `mmtk` module. note that we might want to not spend the time to update the code use the standard `mmtk` module as it is only available in python 2. here is a separate issue to investigate removing this dependency altogether: https://github.com/ISISNeutronMuon/MDANSE/issues/7.

**Comment by perenon** [comment]
FYI MMTK is not compatible with numpy versions after 1.9.0 (so Ubuntu 16.04), due to the use of Numeric (in Scientific.N).
That explains the choice to use a custom version of MMTK, that we modified to get rid of Numeric.

**Comment by eurydice76** [comment]
Anyway, the problem of MMTK in MDANSE is a no-problem as I could get rid of MMTK in the branch protos.

**Comment by MBartkowiakSTFC** [comment]
As noted above, MMTK is not used anymore in Python 3 version of MDANSE.
