### ISSUE TITLE
BUG: The contextual help is broken

### ISSUE THREAD

**Issue by eurydice76** [ISISNeutronMuon/MDANSE#63]
When clicking on the Help button of a job plugin, a small help should be displayed about that job. It does not appear anymore.

**Comment by RastislavTuranyi** [comment]
Can you please provide more detail? I have tested on the latest commit on develop on Windows 10, and the help button works for all analyses and all trajectory conversions that I tried.

**Comment by eurydice76** [comment]
On ubuntu 20.04 using a recent version of sphinx (1.8.6) the building of the doc crashes yielding an empty documentation.
I could solve some of the errors in branch 41 but there is still an error which prevents from getting the complete documentation.

**Comment by RastislavTuranyi** [comment]
I see. In the CI/CD, I use sphinx==1.6.7 and docutils==0.17.1 since that works well. This should be less of an issue with GUI but instead with supporting latest versions of sphinx.

**Comment by eurydice76** [comment]
I just push on branch 63 the changes I did in the other branches. Running python setup.py build_api triggers now the following error:
```
reading sources... [ 79%] MDANSE.GUI.Plugins.MolecularViewerPlugin                                                                                                                                                                                                          
Exception occurred:
  File "/home/pellegrini/condaenvs/mdanse/lib/python2.7/abc.py", line 175, in __subclasscheck__
    if issubclass(subclass, rcls):
TypeError: issubclass() arg 1 must be a class

```
No idea right now why this errors occurs. In earlier version of sphinx the error was already there but was non blocking
