### ISSUE TITLE
BUG: Windows installer does not create shortcut anymore

### ISSUE THREAD

**Issue by eurydice76** [ISISNeutronMuon/MDANSE#74]
The windows installer used to create at the very end of the installation a shortcut to _Institut Laue Langevin/MDANSE_. Now that the target is simply _MDANSE_, the shortcut is not done anymore.

**Comment by eurydice76** [comment]
I fixed the regression introduced in the NSIS installer. It should be OK now. However, I can not test it because my windows machine is not setup for building MDANSE.

**Comment by RastislavTuranyi** [comment]
I do not have this issue; on my laptop the shortcut is created without issues on the [latest CD-generated installer](https://github.com/ISISNeutronMuon/MDANSE/actions/runs/2079303853) when I tick the box to create a shortcut.

**Comment by RastislavTuranyi** [comment]
I have tested your changes and noticed that now the desktop shortcut is created automatically, without my input.

**Comment by eurydice76** [comment]
OK, I will retry on my Windows machine. But it is strange given the changes that has been made on the NSIS file that it still works.
