### ISSUE TITLE
BUG: MacOS CI doesn't fail when tests fail

### ISSUE THREAD

**Issue by eurydice76** [ISISNeutronMuon/MDANSE#87]
Hi @RastislavTuranyi , I met a strange behaviour on the build server during my last commit on branch 75. Indeed, there was a bug in one of the analysis (`StructureFactorFromScatteringFunction.py`) that should have triggered a crash of the corresponding unit test. Surprinsingly, the test succeeded on macos but crashed on Linux/Ubuntu 20.04. This clearly should not happen. It looks like there is some kind of old cache on macos. Could you please investigate ont this ?

**Comment by eurydice76** [comment]
Hi @RastislavTuranyi , there is still something buggy with the build server. Indeed, the last build on develop branch failed at deploy step on linux and macosx. On macos, the bug is related with netCDF4. Could you please investigate on this ? Many thanks

**Comment by RastislavTuranyi** [comment]
The ubuntu deploy issue has been solved in #77, but I will look at MacOS.
